# Generated by Django 4.2.11 on 2024-04-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("cooking_time", models.IntegerField(blank=True, null=True)),
                (
                    "spiciness_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1단계", "1단계"),
                            ("2단계", "2단계"),
                            ("3단계", "3단계"),
                            ("4단계", "4단계"),
                            ("5단계", "5단계"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("calories", models.IntegerField(blank=True, null=True)),
                (
                    "cuisine_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("한식", "한식"),
                            ("양식", "양식"),
                            ("중식", "중식"),
                            ("일식", "일식"),
                            ("퓨전", "퓨전"),
                            ("기타", "기타"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
