# Generated by Django 4.2.11 on 2024-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="ingredients",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cuisine_type",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="spiciness_level",
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="kind",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="material",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="recipe_id",
            field=models.CharField(
                default="1", max_length=20, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="seasonings",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
