# Generated by Django 4.2.11 on 2024-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Amount", models.IntegerField()),
                ("Date_of_registration", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
