# Generated by Django 4.2.11 on 2024-04-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredient_name", models.CharField(max_length=100)),
                ("avg_expiry_date", models.IntegerField()),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("food_type", models.CharField(max_length=50)),
                (
                    "fridge_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
