# Generated by Django 4.2.11 on 2024-04-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="purchase_date",
            new_name="Date_of_registration",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="avg_expiry_date",
            new_name="Expiration_date",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="ingredient_id",
            new_name="ID",
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="ingredient_name",
            new_name="Scategory",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="food_type",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="fridge_location",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="notes",
        ),
        migrations.AddField(
            model_name="ingredient",
            name="Mcategory",
            field=models.CharField(
                choices=[("채소", "채소"), ("과일", "과일"), ("고기", "고기")],
                default="채소",
                max_length=10,
            ),
        ),
    ]
