# Generated by Django 4.2.11 on 2024-04-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ingredient",
            "0002_rename_purchase_date_ingredient_date_of_registration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="Mcategory",
            field=models.CharField(
                choices=[("채소", "채소"), ("과일", "과일"), ("고기", "고기"), ("유제품", "유제품")],
                default="채소",
                max_length=10,
            ),
        ),
    ]
