# Generated by Django 4.2.11 on 2024-04-17 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingredient", "0003_alter_ingredient_mcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="Date_of_registration",
        ),
    ]
